### ISSUE TITLE
skewness formula precedence error

### ISSUE THREAD

**Issue by jlp765** [compute-io/skewness#2]
`return Math.sqrt( N*N-1)*g / (N-2);`

should be 

`return Math.sqrt( N*(N-1))*g / (N-2);`

so that `(N*N) -1` becomes `N*(N-1)`

(I am basing this on comparison to results from Excel and Python Pandas library)

**Comment by kgryte** [comment]
@jlp765 Thanks for finding this bug. Will patch later today.
